In [1]:
import numpy as np
a=np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [2]:
a.ndim

1

In [3]:
a.shape

(6,)

In [4]:
b=a.reshape((3,2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
b.ndim

2

In [6]:
b.shape

(3, 2)

In [7]:
b[1][0]=77
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [8]:
a

array([ 0,  1, 77,  3,  4,  5])

In [9]:
c = a.reshape((3,2)).copy()
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [10]:
c[0][0]=-99
a

array([ 0,  1, 77,  3,  4,  5])

In [11]:
c

array([[-99,   1],
       [ 77,   3],
       [  4,   5]])

In [12]:
a*2

array([  0,   2, 154,   6,   8,  10])

In [13]:
a**2

array([   0,    1, 5929,    9,   16,   25], dtype=int32)

In [14]:
a[np.array([2,3,4])]

array([77,  3,  4])

In [16]:
a>4

array([False, False,  True, False, False,  True])

In [17]:
a[a>4]

array([77,  5])

In [18]:
a.clip(0,4)

array([0, 1, 4, 3, 4, 4])

In [20]:
c = np.array([1,2,np.NAN,3,4]) 
c

array([ 1.,  2., nan,  3.,  4.])

In [21]:
np.isnan(c)

array([False, False,  True, False, False])

In [22]:
c[~np.isnan(c)]

array([1., 2., 3., 4.])

In [23]:
np.mean(c[~np.isnan(c)])

2.5

In [26]:
import scipy , numpy

In [27]:
scipy.version.full_version

'1.5.2'

In [28]:
scipy.dot is numpy.dot

False

In [29]:
import matplotlib.pyplot as plt

In [30]:
plt.scatter(x,y)
plt.titile("Web traffic over the last month")
plt.xlabel("Time")
plt.ylable("Hits/Hour")
plt.xticks([w*7*24 for w in range(101)], ['week %i' %w for w in range(10)])
plt.autoscale(tight=True)
plt.grid()
plt.show()

NameError: name 'x' is not defined