In [1]:
print("Hello")

Hello


In [3]:
import keyword
print(len(keyword.kwlist))

35


In [2]:
import sys
print(sys.version)

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


In [3]:
for a in range(10):
    if a>4:
        print(a)

5
6
7
8
9


In [4]:
a=[[1,2,3],[1,3,4]]
print(a)

[[1, 2, 3], [1, 3, 4]]


In [5]:
b=[1+3,"a"*5,3]
print(b)

[4, 'aaaaa', 3]


In [6]:
y = 10 - 3 + 9 * 8 / 5 
print(y)

21.4


In [7]:
x = (100+3) * 2 + 3 / 5 
print(x)

206.6


In [8]:
fruit = "Apple"
condition1 = "good" 
condition2 = "health"
a=fruit+"\tis\t"+condition1+"\tfor\t"+condition2
print(a)

Apple	is	good	for	health


In [9]:
my_word = "A paragraph is a series of related sentences developing a central idea, called the topic. Try to think about paragraphs in terms of thematic unity: a paragraph is a sentence or a group of sentences that supports one central, unified idea. Paragraphs add one idea at a time to your broader argument."
print(my_word)

A paragraph is a series of related sentences developing a central idea, called the topic. Try to think about paragraphs in terms of thematic unity: a paragraph is a sentence or a group of sentences that supports one central, unified idea. Paragraphs add one idea at a time to your broader argument.


In [10]:
print(my_word.startswith("paragaph"))

False


In [11]:
name="Hong"
if name=="Bisak" or name=="valerie":
    print("My name is either David or Valerie")
else:
    print("Either one of my name")

Either one of my name


In [12]:
a=1/2
b=2/3
c=3/4
d=4/5

if(a>b):
    print("a is greater than b")
if(b>c):
    print("b is greater than c")
if(c>d):
    print("c is greater than d")
if a<b and b<c and c<d:
    print("a smallest number")

a smallest number


In [13]:
a=['foo','bar','baz','qux','corge']
while a:
    if len(a)<3:
        break
    print(a.pop())
print('Done')

corge
qux
baz
Done


In [14]:
error=50
while error>1:
    error=error/4
    print(error)

12.5
3.125
0.78125


In [15]:
print("heo")

heo


In [16]:
print(my_word.startswith("paragaph"))

False


In [17]:
print(my_word[2:11])

paragraph


In [18]:
print(my_word[2:11].upper())

PARAGRAPH


In [19]:
numbers=[2,3,4,5,6]
total=0

for num in numbers:
    total=total+num
print("total number is",total)

total number is 20


In [20]:
class Parrot:
    species= "bird"
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
blu = Parrot("Blu", 10)
woo = Parrot("Woo", 15)

print("Blu is a {}".format(blu.__class__.species))
print("Woo is also a {}".format(woo.__class__.species))
print("{} is {} years old".format( blu.name, blu.age))
print("{} is {} years old".format( woo.name, woo.age)) 

Blu is a bird
Woo is also a bird
Blu is 10 years old
Woo is 15 years old


In [21]:
class Parrot:
# class attribute
    species = "bird"
# instance attribute
    def __init__(self, name, age):
        self.name = name
        self.age = age
# instantiate the Parrot class
blu = Parrot("Blu", 10)
woo = Parrot("Woo", 15)
# access the class attributes
print("Blu is a {}".format(blu.__class__.species))
print("Woo is also a {}".format(woo.__class__.species))
# access the instance attributes
print("{} is {} years old".format( blu.name, blu.age))
print("{} is {} years old".format( woo.name, woo.age))

Blu is a bird
Woo is also a bird
Blu is 10 years old
Woo is 15 years old


In [22]:
class Parrot:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def sing(self, song):
        return "{} sings {}".format(self.name, song)
    def dance(self):
        return "{} is now dancing".format(self.name)
blu=Parrot("chanto",20)

# call our instance methods
print(blu.sing("'Happy'"))
print(blu.dance())

chanto sings 'Happy'
chanto is now dancing


In [23]:
class Parrot:
# instance attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age
# instance method
    def sing(self, song):
        return "{} sings {}".format(self.name, song)
    def dance(self):
        return "{} is now dancing".format(self.name)
# instantiate the object
blu = Parrot("Blu", 10)
# call our instance methods
print(blu.sing("'Happy'"))
print(blu.dance())

Blu sings 'Happy'
Blu is now dancing


In [24]:
class Bird:
    def __init__(self):
        print("Bird is ready")
    def whoisThis(self):
        print("Bird")
    def swim(self):
        print("Swim faster")
# child class
class Penguin(Bird):
    def __init__(self):
# call super() function
        super().__init__()
        print("Penguin is ready")
    def whoisThis(self):
        print("Penguin")
    def run(self):
        print("Run faster")
peggy = Penguin()
peggy.whoisThis()

Bird is ready
Penguin is ready
Penguin


In [25]:
class Dog:
    
    def __init__(self, color, legs):
        self.color= color
        self.legs= legs

bb = Dog("White", 4)
print(bb.color)

White


In [26]:
class Animal:
    def __init__(self, name, color):
        self.name=name
        self.color=color

class Cat(Animal):
    def purr(self):
        print(Cat.purr('3'))   

In [27]:
num1=20
num2=30
sum=num1+num2
print('the sum of {0} and {1} is {2}',sum)

the sum of {0} and {1} is {2} 50


In [28]:
num1=input("Enther the number1")
num2=input("Enther the number2")

sum=float(num1)+float(num2)
print('the sum of {0} and {1} is {2}',sum)

Enther the number15.5
Enther the number24.6
the sum of {0} and {1} is {2} 10.1


num=9
square_root=num**0.5
print('The square root of %0.3f is %0.3f'%(num ,num_sqrt))

In [29]:
num=9 
num_sqrt=num**0.5
print('The square root of %0.3f is %0.3f'%(num ,num_sqrt))

The square root of 9.000 is 3.000


In [30]:
a=float(input("Enter number a\n"))
b=float(input("Enter number b\n"))
c=float(input("Enter numb c\n"))

s=(a+b+c)/2
area=(s*(s-a)*(s-b)*(s-c))**0.5
print('the area of rectangle %0.2f'%area)

Enter number a
5
Enter number b
7
Enter numb c
8
the area of rectangle 17.32


In [31]:
# Python Program to find the area of triangle

#a = 5
#b = 6
#c = 7

# Uncomment below to take inputs from the user
a = float(input('Enter first side: '))
b = float(input('Enter second side: '))
c = float(input('Enter third side: '))

# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print('The area of the triangle is %0.2f'%area)

Enter first side: 6.5
Enter second side: 6.3
Enter third side: 8.1
The area of the triangle is 20.06


In [32]:
import cmath

a=1
b=2
c=3

d=(b**2)-(4*a*c)

sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)
print('the solution are {0} and {1}'.format(sol1,sol2))

the solution are (-1-1.4142135623730951j) and (-1+1.4142135623730951j)


In [33]:
import cmath

a = 1
b = 5
c = 6

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

The solution are (-3+0j) and (-2+0j)


In [34]:
a=9
b=4

temp=a
a=b
b=temp

print('The value of x after swapping: {}'.format(a))
print('The value of y after swapping: {}'.format(b))

The value of x after swapping: 4
The value of y after swapping: 9


In [35]:
n=50
sum=0
i=1

while i<=n:
    sum=sum+i
    i=i+1
print("total", sum)

total 1275


In [36]:
for val in "string":
    if val == "n":
        continue
    print(val)

print("The end")

s
t
r
i
g
The end


In [37]:
def greet():
    print("hello")
    print("what is your name")
greet()

hello
what is your name


In [38]:
def greet(name):
    print("heemloo",name)
greet('chanto')

heemloo chanto


In [39]:
def add(n1,n2):
    sum=n1+n2
    return sum

result=add(4,0)
print(result)

4


In [40]:
def greet(*names):
    for name in names:
        print("Hello", name)
greet("Monica", "Luke", "Steve", "John")

Hello Monica
Hello Luke
Hello Steve
Hello John


In [41]:
def factorial(x):
    
    if x == 1:
        return 1
    else:
        return (x * factorial(x-1))


num = 7
print("The factorial of", num, "is", factorial(num))

The factorial of 7 is 5040


In [42]:
my_list = [1, 5, 4, 6, 8, 11, 3, 12]

new_list = list(filter(lambda x: (x%2 == 0) , my_list))

print(new_list)

[4, 6, 8, 12]


In [43]:
larger=lambda a,b:a if a>b else b
larger(0,7)

7

In [44]:
double = lambda x: x * 2

print(double(5))

10


In [45]:
def outer():
    x = "local"

    def inner():
        nonlocal x
        x = "nonlocal"
        print("inner:", x)

    inner()
    print("outer:", x)


outer()

inner: nonlocal
outer: nonlocal


In [46]:
lists=['a','b','c']
for lan in lists:
    print(lan)

a
b
c


In [47]:
lists.insert(1,"d")
print(lists)

['a', 'd', 'b', 'c']


In [48]:
number1={2,4,5,6}
number2={4,5,3,2}
number1.update(number2)
print(number1)

{2, 3, 4, 5, 6}


In [49]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
print(A & B)

{4, 5}


In [50]:
# Membership Test for Dictionary Keys
squares = {1: 1, 3: 9, 5: 25, 7: 49, 9: 81}

# Output: True
print(1 in squares)

# Output: True
print(2 not in squares)

# membership tests for key only not value
# Output: False
print(49 in squares)

True
True
False


In [51]:
squares = {1: 1, 3: 9, 5: 25, 7: 49, 9: 81}
for i in squares:
    print(squares[i])

1
9
25
49
81


In [52]:
class Student:
    def check_pass_fail(self):
        if self.marks>=40:
            return True
        else:
            return False
    
student1=Student()
student1.name="Harry"
student1.marks=85
did_pass=student1.check_pass_fail()
print(did_pass)

student2=Student()
student2.name="Janet"
student2.marks=30
did_fail=student2.check_pass_fail()
print(did_fail)

True
False


In [53]:
class Student:
    def check_pass_fail(self):
        if self.marks>=40:
            return True
        else:
            return False
        
    def __init__(self,name,marks):
        self.name=name
        self.marks=marks
    
student1=Student("Harry",9)
student2=Student("Janet",90)
did_pass=student1.check_pass_fail()
print(did_pass)
did_fail=student2.check_pass_fail()
print(did_fail)

False
True


In [54]:
class Complex:
    def __init__(self,real,imag):
        self.real= real
        self.imag= imag
        
    def add(self, number):
        real=self.real + number.real
        imag=self.imag + number.imag
        result=Complex(real, imag)
        return result
    
n1=Complex(5,6)
n2=Complex(-4,2)
result=n1.add(n2)
print("real=",result.real)
print("imag=",result.imag)

real= 1
imag= 8


In [55]:
from datetime import date

f_date=date(2014,7,2)
l_date=date(2014,7,11)
delta=l_date-f_date
print(delta.days)

9


In [56]:
def difference(n):
    if n<=17:
        return 17-n
    else:
        return (n-17)*2
    
print(difference(22))
print(difference(14))

10
3


In [57]:
def near_thousand(n):
    return ((abs(1000-n)<=100) or (abs(2000-n)<=100))
print(near_thousand(800))

False


In [58]:
def sum_thrice(x,y,z):
    sum=x+y+z
    
    if x==y==z:
        sum=sum*3
        return sum
print(sum_thrice(1,2,3))
print(sum_thrice(4,4,4))

None
36


In [59]:
def new_string(str):
    if len(str)>=2 and str[:2]=="Is":
        return str
    return "Is"+str

print(new_string("I"))
print(new_string("I"))

IsI
IsI


In [60]:
def larger_string(str,n):
    result=" "
    for i in range(n):
        result=result+str
    return result
print(larger_string(".tito",3))

 .tito.tito.tito


In [61]:
number=int(input("Enter the number :"))


if number%2==0:
    print("this is even number")
else:
    print("this is odd number")

Enter the number :67
this is odd number


In [62]:
def list_count_4(nums):
    count=0
    for num in nums:
        if num==4:
            count=count+1
    return count
print(list_count_4([4,4,4,4]))

4


In [63]:
def is_vowel(char):
    all_vowels='aeiou'
    return char in all_vowels
print(is_vowel('a'))
print(is_vowel('u'))

True
True


In [64]:
def number(numbers,n):
    for value in numbers:
        if n==value:
            return True
    return False
print(number([1,5,3,7],7))
print(number([-4,-2,5,3],0))

True
False


In [65]:
def histogram(items):
    for n in items:
        output=''
        times=n
        while(times>0):
            output+='*'
            times=times-1
        print(output)
histogram([1,2,3,4,5,6,7])

*
**
***
****
*****
******
*******


In [66]:
def add_elements(list):
    result=''
    for elements in list:
        result+=str(elements)
    return result
print(add_elements([1,4,5,7,6,7,8]))

1457678


In [67]:
color_1=set(["white","black","red"])
color_2=set(["red","green"])
print(color_2.difference(color_1))

{'green'}


In [68]:
a=float(input("Input the base:"))
b=float(input("Input the height:"))
area=a*b/2
print("area=",area)

Input the base:5
Input the height:8
area= 20.0


In [69]:
def gcd(x,y):
    gcd=1
    
    if x%y==0:
        return y
    
    for k in range(int(y/2),0,-1):
        if x%k==0 and y%k==0:
            gcd=k
            break 
    return gcd
print(gcd(100,36))

4


In [70]:
def personal_details():
    name,age="chanto",30
    address="Bangalore ,kanataka,India"
    print("Name: {}\nAge: {}\nAddress:{}".format(name,age,address))
    
personal_details()

Name: chanto
Age: 30
Address:Bangalore ,kanataka,India


In [71]:
x,y=5,6
result=x*x+2*x*y+y*y
print("({}+{})^2)={}".format(x,y,result))

(5+6)^2)=121


In [72]:
amt=10000
int=3.5
years=7

future_value=amt*((1+(0.01*int)) ** years)
print(round(future_value,2))

12722.79


In [73]:
import math

x1=[5, 6]
y1=[2, 1]

distance=math.sqrt(((x1[0]-y1[0])**2)+((x1[1]-y1[1])**2))
print(distance)

5.830951894845301


In [74]:
import os.path

open('abc.txt','w')
print(os.path.isfile('abc.txt'))

True


In [75]:
x=5245 //1000
x1=(5245-x*1000)//100
x2=(5245-x*1000-x1*100)//10
x3=5245-x*1000-x1*100-x2*10
print("The sum of digits in the numbers is",x+x1+x2+x3)

The sum of digits in the numbers is 16


In [76]:
x  = 5245//1000
x1 = (5245 - x*1000)//100
x2 = (5245 - x*1000 - x1*100)//10
x3 = 5245 - x*1000 - x1*100 - x2*10
print("The sum of digits in the number is", x+x1+x2+x3)

The sum of digits in the number is 16


In [77]:
numbers=float(input("Input a number"))
if numbers>0:
    print("It is positive number")
elif numbers==0:
    print("It is Zero")
else:
    print("It is a negative number")

Input a number7
It is positive number


In [78]:
nums=[34,1,0,25]
print("original numbers in the lists:",nums)
new_nums=list(filter(lambda y: y>=0 ,nums))
print("Posotive numbers in the list:",new_nums)

original numbers in the lists: [34, 1, 0, 25]
Posotive numbers in the list: [34, 1, 0, 25]


In [79]:
def test_distinct(data):
    if len(data)== len(set(data)):
        return True
    else:
        return False;
print(test_distinct([1,4,5,6]))
print(test_distinct([4,5,5,6,4,9]))

True
False


In [80]:
import random

char_list=['a','e','i','o','u']
random.shuffle(char_list)
print(''.join(char_list))

oiuae


In [81]:
import bs4
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen

news_url="https://news.google.com/news/rss"
Client=urlopen(news_url)
xml_page=Client.read()
Client.close()

soup_page=soup(xml_page,"xml")
news_list=soup_page.findAll("item")
# Print news title, url and publish date
for news in news_list:
  print(news.title.text)
  print(news.link.text)
  print(news.pubDate.text)
  print("-"*60)


Texas Democrats Walk Out, Stop Republican's Sweeping Voting Restrictions - NPR
https://news.google.com/__i/rss/rd/articles/CBMicGh0dHBzOi8vd3d3Lm5wci5vcmcvMjAyMS8wNS8zMS8xMDAxODExOTE5L3RleGFzLWRlbW9jcmF0cy13YWxrLW91dC1zdG9wLXJlcHVibGljYW5zLXN3ZWVwaW5nLXZvdGluZy1yZXN0cmljdGlvbnPSAQA?oc=5
Mon, 31 May 2021 06:09:00 GMT
------------------------------------------------------------
China Announces a Three-Child Policy - The New York Times
https://news.google.com/__i/rss/rd/articles/CBMiS2h0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjEvMDUvMzEvd29ybGQvYXNpYS9jaGluYS10aHJlZS1jaGlsZC1wb2xpY3kuaHRtbNIBT2h0dHBzOi8vd3d3Lm55dGltZXMuY29tLzIwMjEvMDUvMzEvd29ybGQvYXNpYS9jaGluYS10aHJlZS1jaGlsZC1wb2xpY3kuYW1wLmh0bWw?oc=5
Mon, 31 May 2021 08:31:23 GMT
------------------------------------------------------------
Israel coalition government a threat to security, warns Netanyahu - BBC News
https://news.google.com/__i/rss/rd/articles/CBMiM2h0dHBzOi8vd3d3LmJiYy5jb20vbmV3cy93b3JsZC1taWRkbGUtZWFzdC01NzMwMjgxNNIBN2h0dHBzOi

In [83]:
def permute(nums):
    result_perms=[[]]
    for n in nums:
        new_perms=[]
        for perm in result_perms:
            for i in range(len(perm)+1):
                new_perms.append(perm[:i]+[n]+perm[i:])
                result_perms=new_perms
    return result_perms
my_nums=[1,2,3]
print("Original Cofllection:",my_nums)
print("Collection of distinct numbers:\n",permute(my_nums))

Original Cofllection: [1, 2, 3]
Collection of distinct numbers:
 [[3, 2, 1], [2, 3, 1], [2, 1, 3], [3, 1, 2], [1, 3, 2], [1, 2, 3]]


In [84]:
def string_length(str):
    count=0
    for char in str:
        count+= 1
    return count
print(string_length('w3school.com'))

12


In [85]:
def char_frequency(str):
    dict={}
    for n in str:
        keys=dict.keys()
        if n in keys:
            dict[n]+=1
        else:
            dict[n]=1
    return dict
print(char_frequency('google.com'))

{'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}


In [86]:
def string_both_ends(str):
    if(len(str))<2:
        return ''
    return str[0:2]+str[-2:]
print(string_both_ends('w3resource'))
print(string_both_ends('chanto'))

w3ce
chto


In [87]:
def change_char(str):
    char=str[0]
    str=str.replace(char,'$')
    str=char+str[1:]
    
    return str
print(change_char('restart'))

resta$t


In [88]:
def chars_mix_up(a,b):
    new_a=b[:2]+a[2:]
    new_b=a[:2]+b[2:]
    return new_a+'\n'+new_b
print(chars_mix_up('abc','xyz'))

xyc
abz


In [89]:
def not_poor(str1):
    snot=str1.find('not')
    spoor=str1.find('poor')
    
    if spoor > snot and snot>0 and spoor>0:
        str1=str1.replace(str1[snot:(spoor+4)], 'good')
        return str1
    else:
        return str1
print(not_poor('The lyrics is not that poor!'))
print(not_poor('The lyrics is poor!'))

The lyrics is good!
The lyrics is poor!


In [90]:
def find_longest_word(words_list):
    word_len= []
    for n in words_list:
        word_len.append((len(n),n))
    word_len.sort()
    return word_len[-1][0],word_len[-1][1]

result=find_longest_word(["PHP","Exercises","Backend"])
print("\n Longest word:",result[1])
print("length of the longest word:",result[0])                          


 Longest word: Exercises
length of the longest word: 9


In [91]:
a=range(10)

print(type(a))

<class 'range'>


In [92]:
import numpy as np
b_1=np.zeros((2,3))
b_1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [93]:
# with np.ones

b_2=np.ones(5)
b_2

array([1., 1., 1., 1., 1.])

In [94]:
b_3=np.empty(5)
b_3.fill(5)
b_3

array([5., 5., 5., 5., 5.])

In [95]:
b_4=np.full(5,5)

In [96]:
x=np.array([[1,2,3],[2,3,4],[4,5,6]])
x

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [97]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
x=np.array([1,2,3,4])
y=np.array([1,2,3,4])
a=x+y
print(a)

[2 4 6 8]


In [99]:
#Exercise 1: create two array per mothod

x=np.array([[1,2,3],[2,3,4],[4,5,6]])
y=np.array([[2,2,6],[5,6,1],[8,3,4]])
z=x+y
z

array([[ 3,  4,  9],
       [ 7,  9,  5],
       [12,  8, 10]])

In [101]:
np.fromfunction(lambda i, j: i == j, (4, 3), dtype=int)

TypeError: Cannot interpret '3.5' as a data type

In [100]:
g = lambda m, n: n + 10 * m
g_0 =  np.fromfunction(g, (5, 6), dtype=int) # numpy.fromfunction(function, shape, **kwargs)
g_0

TypeError: Cannot interpret '3.5' as a data type

In [ ]:
g_0[:4,2:4]

In [ ]:
g_0[1:4,1:5]

In [ ]:
x=np.array([1,2,3,4])
y=np.array([1,3,5,6,8])
x,y=np.meshgrid(x,y)
x

In [ ]:
y

In [ ]:
from array import *
array_num=array('i',[1,3,5,7,9])
for i in array_num:
    print(i)
print("Access first three itmes individually")
print(array_num[0])
print(array_num[1])
print(array_num[2])

In [ ]:
from array import *
array_num=array('i',[1,3,5,7,9])
print("Original array:"+str(array_num))
print("Append 11 at the end of array:")
array_num.append(11)
print("New array:"+str(array_num))

In [ ]:
from array import *

array_num=array('i',[1,3,5,7,9])
print("original array:"+str(array_num))
print("Length in bytes of one array item:"+str())

In [ ]:
A=np.arange(15)
A

In [ ]:
A[0]

In [ ]:
B=g_0[1:5,1:5]
B

In [ ]:
B[:,:]=0
g_0

In [ ]:
c=B[1:3,1:3]
c

In [ ]:
c[:,:]=0
g_0

In [ ]:
B

In [ ]:
from array import *
array_num=array('i',[1,3,7,5,9])
print("Original array:"+str(array_num))
print("Remove the third item from the arrays:")
array_num.pop(2)
print("New array:"+str(array_num))

In [ ]:
f=np.arange(15)
f

In [ ]:
g=f.reshape(3,5)
print(g)

In [ ]:
h=np.arange(120)
h

In [109]:
h=h.reshape(3,40)
print(h)

NameError: name 'h' is not defined

In [110]:
import numpy as np

In [111]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [108]:
upper, lower =np.vsplit(grid,[3])
print(upper)
print(lower)

NameError: name 'grid' is not defined

In [3]:
a = {1,2,6,8}
b = {2,3,5,8}
print((a) - (b))

{1, 6}


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0])
print(a[:1])
print(a[1:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1 2 3]]
[]


In [10]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[3,4,5],[5,6,7]])
print(b)
print(np.concatenate([a,b],axis=0))
print(np.concatenate([a,b],axis=1))

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [5 6 7]]
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]]
[[1 2 3 3 4 5]
 [4 5 6 5 6 7]]


In [ ]:
print(np.stack(a,b))